### ISSUE TITLE
JuJu Dashboard crashes/errors on model detail page

### ISSUE THREAD

**Issue by GerDner** [canonical/jaas-dashboard#1462]
**Describe the bug**
Dashboard Details views stay empty because of a websocket error `client incompatible with server 3.1.2`. Possibly thrown in https://github.com/juju/juju/blob/a76353413e8741d5497db1e5bd405b2b14402714/apiserver/restrict_newer_client.go

Latest controller and dashboard is used. Only a view websockets calls produce this error (mostly `type: "Annotations"`). Most calls are fine.

**To Reproduce**
1. Deploy a new controller on aws cloud (problem was reproducible on local lxd cloud too)
2. deploy the dashboard charm and relate it
3. open dashboard charm via proxy or expose it
4. login and click on a model

Problem also occurs, then the controller is registered on [jaas](https://jaas.ai/).

**Expected behavior**
Model Details like logs/actions are shown

**Screenshots**

Request
```json
{"type":"Annotations","request":"Get","version":2,"params":{"entities":[{"tag":"application-controller"},{"tag":"application-juju-dashboard"}]},"request-id":3}

```

Response
```json
{"request-id":3,"error":"client incompatible with server 3.1.2","error-code":"incompatible client","error-info":{"server-version":"3.1.2"},"response":{}}
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22 LTS on local and on all machines
 - Browser: Chrome latest (112)
 - Version: JuJu 3.1.2 snap

**Additional context**

Bundle-export:

```yaml
series: jammy
applications:
  controller:
    charm: juju-controller
    channel: 3.1/stable
    revision: 14
    num_units: 1
    to:
    - "0"
    expose: true
    options:
      controller-url: wss://3.76.216.245:17070/api
      identity-provider-url: ""
      is-juju: true
    constraints: arch=amd64 mem=3584
    trust: true
  juju-dashboard:
    charm: juju-dashboard
    channel: stable
    revision: 10
    num_units: 1
    to:
    - "0"
    expose: true
    constraints: arch=amd64
machines:
  "0":
    constraints: mem=3584
relations:
- - juju-dashboard:controller
  - controller:dashboard
```
